apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: web-backend-config
  namespace: production

spec:
  timeoutSec: 30
  securityPolicy:
    name: customer-traffic-waf
  logging:
    enable: true
    sampleRate: 1.0
  connectionDraining:
    drainingTimeoutSec: 60

  healthCheck:
    requestPath: /health
    port: 8080
    type: HTTP
    checkIntervalSec: 15
    timeoutSec: 5
