apiVersion: networking.k8s.io/v1
kind: MultiClusterIngress
metadata:
  name: production-ingress
  namespace: production

  annotations:
    networking.gke.io/static-ip: customer-traffic-ip
    networking.gke.io/managed-certificates: production-cert

spec:
  template:
    spec:
      backend:
        serviceName: webapp-a
        servicePort: 80
      rules:
      - host: app.example.com
        http:
          paths:
          - path: /webapp-a/*
            backend:
              serviceName: webapp-a
              servicePort: 80
          - path: /webapp-b/*
            backend:
              serviceName: webapp-b
              servicePort: 80
