apiVersion: v1
kind: Service
metadata:
  name: webapp-b-service
  namespace: production
  annotations:
    cloud.google.com/backend-config: '{"default":"web-backend-config"}'

spec:
  selector:
    app: webapp-b

  ports:
  - port: 80
    targetPort: 8080

  type: ClusterIP
