apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  ENV: "production"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "redis.production.svc.cluster.local"
  PROJECT_ID: "iris-gke-production"
