apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-workload-sa
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: workload-sa@iris-gke-production.iam.gserviceaccount.com
