apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-a
  namespace: production
spec:
  replicas: 3
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: webapp-a

  template:
    metadata:
      labels:
        app: webapp-a

    spec:
      serviceAccountName: gke-workload-sa

      containers:
      - name: webapp-a
        image: us-central1-docker.pkg.dev/iris-gke-production/production-images/webapp-a:latest

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15

        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
